### ISSUE TITLE
Surname validation error

### ISSUE THREAD

**Issue by chrisvidal** [TohurTV/oc-socialconnect-plugin#2]
Hi there,

I am using the Facebook provider only and I am encountering this validation error `Surname validation error` upon FB Login, where `surname field is required`.  My users are using the `username` field to login and not the email field. Is it related?

```php

36 | Illuminate\Support\Facades\Facade::__callStatic(…) | ~/plugins/tohur/socialconnect/classes/UserManager.php | 129
-- | -- | -- | --
35 | Tohur\SocialConnect\Classes\UserManager->registerUser(…) | ~/plugins/tohur/socialconnect/classes/UserManager.php | 66
34 | Tohur\SocialConnect\Classes\UserManager->find(…) | ~/plugins/tohur/socialconnect/routes.php

```

**Comment by chrisvidal** [comment]
OK, I found out that this is another plugin who is extending Rainlab User and make `surname` required. 

closing

**Comment by chrisvidal** [comment]
Still got this issue ~ anyone facing that problem?

**Comment by tohurtv** [comment]
I will setup a test site soon and hammer this out if I get the issue. also I just updated the entire plugin so the Facebook issues may be gone

**Comment by tohurtv** [comment]
Do believe I need to make class extension with custom user mappings like a few the providers already will be working on this and pushing a update out once I have it ready

**Comment by tohurtv** [comment]
This Should be fixed if not please put another bug report in
