### ISSUE TITLE
Column not found: 1054 Unknown column 'provider_userid' in 'field list'

### ISSUE THREAD

**Issue by chrisvidal** [TohurTV/oc-socialconnect-plugin#8]
when I tried to login using FB, this is the exception I am facing.
It was working fine before the update.

```php
in /var/www/html/eclia/plugins/tohur/socialconnect/vendor/laravel/socialite/src/Two/AbstractProvider.php on line 210
```

```php
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'provider_userid' in 'field list' in /var/www/html/eclia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77
```

**Comment by tohurtv** [comment]
ok will find the issue it has to do with the migrations as you stated in the other post. will do some back tracking and make new migrations for people upgrading

**Comment by tohurtv** [comment]
the easiest way to fix this for now and I should update the plugin page to so is run php artisan plugin:refresh Tohur.SocialConnect. this will reset the tables for the plugin and install the new fields but if everyones user info is the same it will still log them into the proper accounts. Do a backup before the refresh just to be sure. In the future I will be handling migrations better
